[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"